/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <fincu/time/calendars/argentina.hpp>
#include <fincu/time/calendars/australia.hpp>
#include <fincu/time/calendars/bespokecalendar.hpp>
#include <fincu/time/calendars/brazil.hpp>
#include <fincu/time/calendars/canada.hpp>
#include <fincu/time/calendars/china.hpp>
#include <fincu/time/calendars/czechrepublic.hpp>
#include <fincu/time/calendars/denmark.hpp>
#include <fincu/time/calendars/finland.hpp>
#include <fincu/time/calendars/germany.hpp>
#include <fincu/time/calendars/hongkong.hpp>
#include <fincu/time/calendars/hungary.hpp>
#include <fincu/time/calendars/iceland.hpp>
#include <fincu/time/calendars/india.hpp>
#include <fincu/time/calendars/indonesia.hpp>
#include <fincu/time/calendars/israel.hpp>
#include <fincu/time/calendars/italy.hpp>
#include <fincu/time/calendars/japan.hpp>
#include <fincu/time/calendars/jointcalendar.hpp>
#include <fincu/time/calendars/mexico.hpp>
#include <fincu/time/calendars/newzealand.hpp>
#include <fincu/time/calendars/norway.hpp>
#include <fincu/time/calendars/nullcalendar.hpp>
#include <fincu/time/calendars/poland.hpp>
#include <fincu/time/calendars/romania.hpp>
#include <fincu/time/calendars/russia.hpp>
#include <fincu/time/calendars/saudiarabia.hpp>
#include <fincu/time/calendars/singapore.hpp>
#include <fincu/time/calendars/slovakia.hpp>
#include <fincu/time/calendars/southafrica.hpp>
#include <fincu/time/calendars/southkorea.hpp>
#include <fincu/time/calendars/sweden.hpp>
#include <fincu/time/calendars/switzerland.hpp>
#include <fincu/time/calendars/taiwan.hpp>
#include <fincu/time/calendars/target.hpp>
#include <fincu/time/calendars/turkey.hpp>
#include <fincu/time/calendars/ukraine.hpp>
#include <fincu/time/calendars/unitedkingdom.hpp>
#include <fincu/time/calendars/unitedstates.hpp>
#include <fincu/time/calendars/weekendsonly.hpp>

